import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { ensureDatabase } from "@/db/ensure";
import { vehicleImages } from "@/db/schema";
import { requireAdminApi } from "@/lib/auth";
import { audit } from "@/lib/data";

const allowed=new Set(["image/jpeg","image/png","image/webp","image/avif"]);const maxBytes=10*1024*1024;
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdminApi();if(!admin)return NextResponse.json({message:"Unauthorised"},{status:401});const bucket=(env as unknown as {VEHICLE_IMAGES?:R2Bucket}).VEHICLE_IMAGES;if(!bucket)return NextResponse.json({message:"Image storage is not configured"},{status:503});const {id:vehicleId}=await params;const form=await request.formData();const file=form.get("file");const altText=String(form.get("altText")||"").trim();if(!(file instanceof File)||!allowed.has(file.type)||file.size>maxBytes||!altText)return NextResponse.json({message:"Use a JPEG, PNG, WebP or AVIF up to 10 MB and provide alt text."},{status:422});await ensureDatabase();const extension=file.type.split("/")[1].replace("jpeg","jpg"),imageId=crypto.randomUUID(),storageKey=`vehicles/${vehicleId}/${imageId}.${extension}`;await bucket.put(storageKey,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=86400"}});const existing=await getDb().select().from(vehicleImages).where(eq(vehicleImages.vehicleId,vehicleId));await getDb().insert(vehicleImages).values({id:imageId,vehicleId,storageKey,altText,displayOrder:existing.length,isPrimary:existing.length===0,createdAt:new Date().toISOString()});await audit(admin.id,"vehicle.image_uploaded","vehicle",vehicleId,{imageId,contentType:file.type,size:file.size});return NextResponse.json({ok:true,id:imageId});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdminApi();if(!admin)return NextResponse.json({message:"Unauthorised"},{status:401});const {id:vehicleId}=await params;const body=await request.json() as {images?:Array<{id:string;displayOrder:number;isPrimary:boolean;altText?:string}>};if(!Array.isArray(body.images)||body.images.length>50)return NextResponse.json({message:"Invalid image order"},{status:422});await ensureDatabase();const db=getDb();for(const image of body.images)await db.update(vehicleImages).set({displayOrder:Math.max(0,Math.trunc(image.displayOrder)),isPrimary:Boolean(image.isPrimary),altText:image.altText?.trim()||undefined}).where(and(eq(vehicleImages.id,image.id),eq(vehicleImages.vehicleId,vehicleId)));await audit(admin.id,"vehicle.images_reordered","vehicle",vehicleId,{count:body.images.length});return NextResponse.json({ok:true});}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdminApi();if(!admin)return NextResponse.json({message:"Unauthorised"},{status:401});const {id:vehicleId}=await params;const imageId=new URL(request.url).searchParams.get("imageId");if(!imageId)return NextResponse.json({message:"Image id required"},{status:400});await ensureDatabase();const db=getDb();const image=await db.query.vehicleImages.findFirst({where:and(eq(vehicleImages.id,imageId),eq(vehicleImages.vehicleId,vehicleId))});if(!image)return NextResponse.json({message:"Not found"},{status:404});const bucket=(env as unknown as {VEHICLE_IMAGES?:R2Bucket}).VEHICLE_IMAGES;if(bucket)await bucket.delete(image.storageKey);await db.delete(vehicleImages).where(eq(vehicleImages.id,imageId));await audit(admin.id,"vehicle.image_deleted","vehicle",vehicleId,{imageId});return NextResponse.json({ok:true});}
