"use client";
import Link from "next/link";
import { useState } from "react";
import type { Enquiry, Vehicle } from "@/db/schema";
import { StatusBadge } from "@/app/components/StatusBadge";

export function AdminDashboard({initialVehicles,initialEnquiries,counts}:{initialVehicles:Vehicle[];initialEnquiries:Enquiry[];counts:{available:number;drafts:number;sold:number;newEnquiries:number}}){const [vehicleRows,setVehicleRows]=useState(initialVehicles);const [enquiryRows,setEnquiryRows]=useState(initialEnquiries);const [message,setMessage]=useState("");
async function vehicleAction(id:string,action:string){setMessage("Working…");const res=await fetch(`/api/admin/vehicles/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const data=await res.json() as {ok?:boolean;message?:string;id?:string};if(!res.ok){setMessage(data.message||"Action failed");return;}if(action==="archive")setVehicleRows(rows=>rows.filter(v=>v.id!==id));else if(action==="duplicate"){setMessage("Draft duplicated. Open it from the refreshed dashboard.");return;}else setVehicleRows(rows=>rows.map(v=>v.id===id?{...v,published:action==="unpublish"?false:true,availabilityStatus:action==="sold"?"sold":action==="under_offer"?"under_offer":action==="publish"&&v.availabilityStatus==="draft"?"in_stock":v.availabilityStatus}:v));setMessage("Vehicle updated.");}
async function enquiryAction(id:string,status:string,note:string){setMessage("Saving enquiry…");const res=await fetch(`/api/admin/enquiries/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,note})});if(res.ok){setEnquiryRows(rows=>rows.map(e=>e.id===id?{...e,status,updatedAt:new Date().toISOString()}:e));setMessage("Enquiry updated.");}else setMessage("Enquiry update failed.");}
return <><div className="admin-title"><div><p className="eyebrow">Protected administration</p><h1>Dashboard</h1></div><Link className="button" href="/admin/vehicles/new">Create vehicle</Link></div><p role="status" aria-live="polite" className="muted">{message}</p><div className="metric-grid"><div className="metric"><span>Available</span><strong>{counts.available}</strong></div><div className="metric"><span>Drafts</span><strong>{counts.drafts}</strong></div><div className="metric"><span>Sold</span><strong>{counts.sold}</strong></div><div className="metric"><span>New enquiries</span><strong>{counts.newEnquiries}</strong></div></div><section className="admin-section"><div className="section-heading"><h2>Vehicles</h2></div><table className="admin-table"><thead><tr><th>Vehicle</th><th>Status</th><th>Published</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{vehicleRows.map(v=><tr key={v.id}><td><strong>{v.year} {v.make} {v.model}</strong><br/><span className="muted">{v.stockNumber}{v.isSample?" · SAMPLE":""}</span></td><td><StatusBadge status={v.availabilityStatus}/></td><td>{v.published?"Yes":"No"}</td><td>{new Intl.DateTimeFormat("en-AU").format(new Date(v.updatedAt))}</td><td><div className="admin-actions"><Link href={`/admin/vehicles/${v.id}`}>Edit</Link>{v.published?<button onClick={()=>vehicleAction(v.id,"unpublish")}>Unpublish</button>:<button onClick={()=>vehicleAction(v.id,"publish")}>Publish</button>}<button onClick={()=>vehicleAction(v.id,"under_offer")}>Under offer</button><button onClick={()=>vehicleAction(v.id,"sold")}>Sold</button><button onClick={()=>vehicleAction(v.id,"duplicate")}>Duplicate</button><button onClick={()=>vehicleAction(v.id,"archive")}>Archive</button></div></td></tr>)}</tbody></table></section><section className="admin-section"><div className="section-heading"><h2>Recent enquiries</h2></div><table className="admin-table"><thead><tr><th>Person</th><th>Enquiry</th><th>Status</th><th>Notification</th><th>Update</th></tr></thead><tbody>{enquiryRows.map(e=><EnquiryRow key={e.id} enquiry={e} onSave={enquiryAction}/>)}</tbody></table></section></>}

function EnquiryRow({enquiry,onSave}:{enquiry:Enquiry;onSave:(id:string,status:string,note:string)=>void}){const [status,setStatus]=useState(enquiry.status);const [note,setNote]=useState("");return <tr><td><strong>{enquiry.name}</strong><br/><a href={`mailto:${enquiry.email}`}>{enquiry.email}</a><br/><a href={`tel:${enquiry.phone}`}>{enquiry.phone}</a></td><td><span className="muted">{enquiry.stateOrPostcode} · prefers {enquiry.preferredContactMethod}</span><p>{enquiry.message}</p><small>Ref {enquiry.id.slice(0,8)}</small></td><td><select value={status} onChange={e=>setStatus(e.target.value)} aria-label={`Status for enquiry ${enquiry.id}`}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="appointment_arranged">Appointment arranged</option><option value="closed_won">Closed won</option><option value="closed_lost">Closed lost</option><option value="spam">Spam</option></select></td><td>{enquiry.notificationStatus}</td><td><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} maxLength={3000} placeholder="Internal note" aria-label={`Internal note for ${enquiry.name}`}/><button onClick={()=>{onSave(enquiry.id,status,note);setNote("")}}>Save</button></td></tr>}
