"use client";
import { FormEvent, useState } from "react";
import Image from "next/image";
import type { vehicleImages } from "@/db/schema";
type ImageRow=typeof vehicleImages.$inferSelect;
export function ImageManager({vehicleId,initialImages}:{vehicleId:string;initialImages:ImageRow[]}){const [images,setImages]=useState(initialImages);const [message,setMessage]=useState("");async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Uploading…");const data=new FormData(e.currentTarget);const response=await fetch(`/api/admin/vehicles/${vehicleId}/images`,{method:"POST",body:data});const result=await response.json() as {ok?:boolean;message?:string};if(response.ok){setMessage("Image uploaded. Refreshing…");location.reload();}else setMessage(result.message||"Upload failed.");}
async function remove(id:string){const response=await fetch(`/api/admin/vehicles/${vehicleId}/images?imageId=${id}`,{method:"DELETE"});if(response.ok){setImages(rows=>rows.filter(i=>i.id!==id));setMessage("Image deleted.");}else setMessage("Delete failed.");}
async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=images.length)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];const ordered=next.map((image,i)=>({...image,displayOrder:i,isPrimary:i===0}));setImages(ordered);await fetch(`/api/admin/vehicles/${vehicleId}/images`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({images:ordered.map(i=>({id:i.id,displayOrder:i.displayOrder,isPrimary:i.isPrimary,altText:i.altText}))})});setMessage("Image order saved; first image is primary.");}
return <section className="admin-section"><h2>Vehicle images</h2><p className="muted">JPEG, PNG, WebP or AVIF only, maximum 10 MB. The first image is primary. SVG uploads are blocked.</p><form className="admin-form" onSubmit={upload}><label>Image<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></label><label>Alt text<input name="altText" required maxLength={180} placeholder="Describe this exact vehicle and view"/></label><button className="button" type="submit">Upload image</button></form><p role="status">{message}</p><div className="vehicle-grid">{images.map((image,index)=><div className="vehicle-card" key={image.id}><Image unoptimized src={`/api/images/${image.storageKey}`} alt={image.altText} width={image.width||1200} height={image.height||800}/><div className="vehicle-card-body"><p>{image.altText}</p><div className="admin-actions"><button onClick={()=>move(index,-1)} disabled={index===0}>Move up</button><button onClick={()=>move(index,1)} disabled={index===images.length-1}>Move down</button><button onClick={()=>remove(image.id)}>Delete</button></div></div></div>)}</div></section>}
