import { NextResponse } from "next/server";
import { and, eq, isNull } from "drizzle-orm";
import { getDb } from "@/db";
import { ensureDatabase } from "@/db/ensure";
import { slugRedirects, vehicles } from "@/db/schema";
import { requireAdminApi } from "@/lib/auth";
import { audit } from "@/lib/data";
import { vehicleSchema } from "@/lib/validation";

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdminApi();if(!admin)return NextResponse.json({message:"Unauthorised"},{status:401});await ensureDatabase();const {id}=await params;const db=getDb();const current=await db.query.vehicles.findFirst({where:and(eq(vehicles.id,id),isNull(vehicles.archivedAt))});if(!current)return NextResponse.json({message:"Not found"},{status:404});const body=await request.json() as {action?:string;data?:unknown};const now=new Date().toISOString();if(body.action){if(body.action==="duplicate"){const copyId=crypto.randomUUID(),slug=`${current.slug}-copy-${Date.now().toString().slice(-5)}`,stockNumber=`${current.stockNumber}-COPY-${Date.now().toString().slice(-4)}`;await db.insert(vehicles).values({...current,id:copyId,slug,stockNumber,published:false,publishedAt:null,availabilityStatus:"draft",featured:false,isSample:false,createdAt:now,updatedAt:now});await audit(admin.id,"vehicle.duplicated","vehicle",copyId,{sourceId:id});return NextResponse.json({ok:true,id:copyId});}const changes:Record<string,unknown>={updatedAt:now};if(body.action==="publish")Object.assign(changes,{published:true,publishedAt:current.publishedAt||now,availabilityStatus:current.availabilityStatus==="draft"?"in_stock":current.availabilityStatus});else if(body.action==="unpublish")Object.assign(changes,{published:false});else if(body.action==="sold")Object.assign(changes,{published:true,availabilityStatus:"sold"});else if(body.action==="under_offer")Object.assign(changes,{published:true,availabilityStatus:"under_offer"});else if(body.action==="archive")Object.assign(changes,{published:false,archivedAt:now});else return NextResponse.json({message:"Unsupported action"},{status:400});await db.update(vehicles).set(changes).where(eq(vehicles.id,id));await audit(admin.id,`vehicle.${body.action}`,"vehicle",id);return NextResponse.json({ok:true});}
const parsed=vehicleSchema.safeParse(body.data);if(!parsed.success)return NextResponse.json({message:"Please check the vehicle information",errors:parsed.error.flatten().fieldErrors},{status:422});if(parsed.data.slug!==current.slug)await db.insert(slugRedirects).values({oldSlug:current.slug,vehicleId:id,createdAt:now}).onConflictDoNothing();await db.update(vehicles).set({...parsed.data,bodyType:parsed.data.bodyType||null,fuelType:parsed.data.fuelType||null,transmission:parsed.data.transmission||null,drivetrain:parsed.data.drivetrain||null,priceCents:parsed.data.priceCents??null,publishedAt:parsed.data.published?(current.publishedAt||now):current.publishedAt,updatedAt:now}).where(eq(vehicles.id,id));await audit(admin.id,"vehicle.updated","vehicle",id,{slugChanged:parsed.data.slug!==current.slug});return NextResponse.json({ok:true,id});}

export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdminApi();if(!admin)return NextResponse.json({message:"Unauthorised"},{status:401});const {id}=await params;await ensureDatabase();await getDb().update(vehicles).set({published:false,archivedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}).where(eq(vehicles.id,id));await audit(admin.id,"vehicle.archived","vehicle",id);return NextResponse.json({ok:true});}
